<?php

/**
 * @file
 * Contains submissions.module.
 */

use Drupal\Core\Link;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;

/**
 * Implements hook_help().
 */
function submissions_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the submissions module.
    case 'help.page.submissions':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Tinda submission entities') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function submissions_preprocess_paragraph(&$variables) {

  // Preprocess the uploaded file value to be link to the uploaded file.
  if (\Drupal::routeMatch()->getRouteName() === 'entity.submission.canonical') {

    if (!empty($variables['elements']['field_question'])) {

      $question = $variables['elements']['field_question'][0]['#options']['entity'];

      if ($question->get('type')->getValue()[0]['target_id'] === 'upload'
        && !empty($variables['content']['field_filler_answers'])
      ) {

        foreach ($variables['content']['field_filler_answers'] as $elementKey => $elementValue) {

          if (is_numeric($elementKey)) {
            $link = &$variables['content']['field_filler_answers'][$elementKey]['#context']['value'];

            if ($link !== NULL) {

              $url = file_create_url($link);

              $link = Link::fromTextAndUrl(
                $url,
                Url::fromUri(
                  $url, ['attributes' => ['target' => '_blank']]
                )
              )->toString();

            }

          }

        }

      }

    }

  }
}
